apiVersion: apps/v1
kind: Deployment
metadata:
  name: soa-registry
  namespace: soa
spec:
  replicas: 3
  selector:
    matchLabels:
      app: soa-registry
  template:
    metadata:
      labels:
        app: soa-registry
    spec:
      containers:
        - name: soa-registry
          image: sheiun/soa-registry:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
          command: ["python", "app.py"]
