apiVersion: v1
kind: Service
metadata:
  name: service-registry
  namespace: service-registry
spec:
  selector:
    app: service-registry
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: NodePort
