apiVersion: v1
kind: Service
metadata:
  name: soa-registry
  namespace: soa
spec:
  selector:
    app: soa-registry
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: NodePort
